[build]
builder = "nixpacks"
buildCommand = "cd server && pnpm install && pnpm build"

[deploy]
startCommand = "cd server && pnpm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "carpool-social-backend"

[services.variables]
NODE_ENV = "production"
PORT = "8080"
