services:
  - type: web
    name: carpool-social-backend
    env: node
    buildCommand: cd server && pnpm install && pnpm build
    startCommand: cd server && pnpm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: carpool-social-db
          property: connectionString
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false

databases:
  - name: carpool-social-db
    databaseName: carpool_social
    plan: free
